In [43]:
# Import numpy and create arrays

import numpy as np

# Create a 1D array(vector)

sales = np.array([200, 450, 300, 500, 800])

# Create a 2D array (matrix)

costs = np.array([
    [100, 220],
    [200, 180],
    [150, 140]
])

In [44]:
# Perform vectorized operations (No loops)

profits = sales - 0.3 * sales
print("After tax profits:", profits)

After tax profits: [140. 315. 210. 350. 560.]


In [45]:
# Array slicing

print("first sale:", sales[0]) # Returns the first sale
print("second sale", sales[1]) # Returns second sale entry
print("last sale:", sales[-1]) # Returns last sale
print("second last sale:", sales[-2]) # Returns second last sale
print("2nd to 4th sales:", sales[1:4]) # Returns second to forth sales

first sale: 200
second sale 450
last sale: 800
second last sale: 500
2nd to 4th sales: [450 300 500]


In [46]:
# Array slicing
print(costs[1:3])
print(costs[0])
print(costs[-1])

[[200 180]
 [150 140]]
[100 220]
[150 140]


In [47]:
# Numpy functions

print("Average Sales:", np.mean(sales))
print("Highest Sale:", np.max(sales))
print("Lowest Sale:", np.min(sales))
print("Standard deviation:", np.std(sales))
print("Total Sales:", sum(sales))

Average Sales: 450.0
Highest Sale: 800
Lowest Sale: 200
Standard deviation: 204.93901531919198
Total Sales: 2250


In [48]:
# Reshaping and shape checking


print(costs.shape)
sales_reshaped = sales.reshape(5, 1)
print(sales_reshaped)
costs_reshaped = costs.reshape(2,3)
print(costs_reshaped)
print(sales_reshaped.shape)
print(sales_reshaped)
print(sales.shape)
print(sales)


(3, 2)
[[200]
 [450]
 [300]
 [500]
 [800]]
[[100 220 200]
 [180 150 140]]
(5, 1)
[[200]
 [450]
 [300]
 [500]
 [800]]
(5,)
[200 450 300 500 800]


In [49]:
# Broadcasting; Add bonus of 50 to all sales

bonus_sales = sales + 50
print(bonus_sales)

[250 500 350 550 850]


In [50]:
# Comparison and filtering

# Categorize high sales as those that are above 400

high_sales = sales[sales > 400]
print("High record sales:", high_sales)

# Categorize sales below 500 as low selling

low_sales = bonus_sales[bonus_sales < 500]
print("Low selling products:", low_sales)

High record sales: [450 500 800]
Low selling products: [250 350]


In [51]:
# Create a numpy array 

import numpy as np

monthly_expenses = np.array([12000, 11000, 10500, 13000, 9500])

print("Monthly expenses:", monthly_expenses)

# Calculate average and standard deviation.

print("Average Monthly expenses:", np.mean(monthly_expenses))
print("Standard deviation:", np.std(monthly_expenses))

Monthly expenses: [12000 11000 10500 13000  9500]
Average Monthly expenses: 11200.0
Standard deviation: 1208.3045973594571


In [52]:
# Subtract each value from a monthly budget (say KSh 15,000)

Disposable_income = 15000 - monthly_expenses
print("Money left every month:", Disposable_income)

Money left every month: [3000 4000 4500 2000 5500]


In [53]:
# Find which months were under budget.

underbudget_months = monthly_expenses[monthly_expenses > 15000]
print("Under budget months:", underbudget_months)

Under budget months: []


In [54]:
# Reshape the data into a column format.

monthly_expenses_reshaped = monthly_expenses.reshape(5,1)
print(monthly_expenses_reshaped)

[[12000]
 [11000]
 [10500]
 [13000]
 [ 9500]]


In [55]:
# Save as .npy file: np.save("monthly_expenses.npy", expenses_array)

np.save("monthly_expenses.npy", monthly_expenses_reshaped)

In [56]:
# Numpy files have a hard time loading on my VS Code. This is the way to load it

import numpy as np
MONTHLY_EXPENSES = np.load('monthly_expenses.npy')
print(MONTHLY_EXPENSES)  # View array contents

[[12000]
 [11000]
 [10500]
 [13000]
 [ 9500]]
